
import { IMenuItem } from "../_interfaces/i-menu-item";
import { Menu } from "./menu";

export class MenuItem implements IMenuItem{
  constructor (
    public menuItemName: string,
    public isDivider: boolean,
    /*
      isHeader true: this item is not an <a> element
      (no action is linkes ...)
    */
    public isHeader: boolean,
    public hasLabelLeft: boolean,
     /*
      label subclass - in daisyUI label has class badge, here we have badge-xxxx subclass
    */
    public labelClassLeft: string,
    public labelTextLeft: string,
    public hasIconLeft: boolean,
    public iconClassLeft: string,
    public text: string,
    /*
      description is displayed as tooltip
    */
    public description: string,
    public link: string,
    public hasIconRight: boolean,
    public iconClassRight: string,
    public hasLabelRight: boolean,
    /*
      label subclass - in daisyUI label has class badge, here we have badge-xxxx subclass
    */
    public labelClassRight: string,
    public labelTextRight: string,
    public hasSubMenu: boolean,
    /*
      in case of directory type
    */
    public subMenuDirectoryHandle: FileSystemDirectoryHandle | null,
    /*
       in case of file type
     */
    public fileHandle: FileSystemFileHandle | null,
    /* 0 = default, undefined,
      other types see enum menu-item-type
     */
    public type: number,
    /* 0 = default, active,
    9 automatic disabled (invalidated, e.g. if issue becomes invalid) */
    public status: number,
    /**
     * for menuStruct in menu service we convert all subMenus to (manifested) subMenu by Id
     *  with menuIds which are generated by menu service
     */
    public subMenuId?: number,
    /*
      subMenuName is necessary only if we build a menu structure with an external json menu file
      where sub menus are identified by names ...
    */
    public subMenuName?: string,
    /**
     * sub menu itself can be placed here to form a complete tree
     * (menuId of subMenu is irrelevant, can be 0)
     *
     * subMenu is used to load menu structure from a external json file (or intermediate prepare a menu structure)
     * which is converted by "buildSubmenus" into a manifested menu structure
     */
    public subMenu?: Menu,
    public isSubMenuLeft?: boolean,
    public isSubMenuRight?: boolean,
    public isSelected?: boolean
  ) { }
}
